package com.example.data

import android.content.Context
import androidx.room.Room
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.firstOrNull
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.SharedFlow
import kotlinx.coroutines.flow.asSharedFlow
import java.util.UUID

class KortanaRepository(context: Context) {
    private val appContext = context.applicationContext

    private val db = Room.databaseBuilder(
        context.applicationContext,
        KortanaDatabase::class.java,
        "kortana_database"
    ).addMigrations(KortanaDatabase.MIGRATION_9_10)
        .fallbackToDestructiveMigration()
        .build()

    private val dao = db.kortanaDao()

    // Expose DB Flows
    val stateFlow: Flow<KortanaState?> = dao.getStateFlow()
    val memoriesFlow: Flow<List<Memory>> = dao.getAllMemoriesFlow()
    val chatMessagesFlow: Flow<List<ChatMessage>> = dao.getChatMessagesFlow()
    val scriptsFlow: Flow<List<SynapticScript>> = dao.getAllScriptsFlow()
    val projectsFlow: Flow<List<KortanaProject>> = dao.getAllProjectsFlow()
    val personalityFlow: Flow<KortanaPersonality?> = dao.getPersonalityFlow()

    // Level up event broadcasting
    private val _levelUpEvent = MutableSharedFlow<Int>(extraBufferCapacity = 1)
    val levelUpEvent: SharedFlow<Int> = _levelUpEvent.asSharedFlow()

    suspend fun getOrCreateState(): KortanaState {
        return dao.getState() ?: KortanaState().also { dao.saveState(it) }
    }

    suspend fun getOrCreatePersonality(): KortanaPersonality {
        return dao.getPersonality() ?: KortanaPersonality().also { dao.savePersonality(it) }
    }

    suspend fun processUserMessage(messageText: String, imageBase64: String? = null, mimeType: String = "image/jpeg"): KortanaTurnResult {
        // 1. Persist User Message
        val userMsg = ChatMessage(sender = "USER", message = messageText)
        dao.insertChatMessage(userMsg)

        // 2. Fetch current state and memory context
        val currentState = getOrCreateState()
        val memories = dao.getAllMemories()
        val chatHistory = dao.getChatMessagesFlow().firstOrNull() ?: emptyList()

        // 3. Query the routing brain (Ollama local -> Claude backup -> Gemini last resort)
        val result = KortanaBrain.queryKortana(appContext, messageText, currentState, memories, chatHistory, imageBase64, mimeType)

        // 4. Persist Kortana's Response
        val kortanaMsg = ChatMessage(sender = "KORTANA", message = result.reply)
        dao.insertChatMessage(kortanaMsg)

        // 5. Persist learned facts
        result.learnedFacts.forEach { fact ->
            if (fact.isNotBlank()) {
                dao.insertMemory(Memory(fact = fact, category = "USER"))
            }
        }

        // 6. Update Kortana's State (XP, Level, Mood, Energy)
        var newXp = currentState.experience + result.xpEarned
        var newLevel = currentState.level
        var leveledUp = false

        // Check level up: nextLevelXp is level * 100
        while (newXp >= newLevel * 100) {
            newXp -= newLevel * 100
            newLevel++
            leveledUp = true
        }

        // Decrease energy by 4-8% per turn, minimum 0
        val newEnergy = (currentState.energy - (4..8).random()).coerceAtLeast(0)

        // Process self-modifying scripts if generated by her neural core
        var customColorOverride: String? = null
        result.dynamicMutation?.let { mut ->
            var finalPurpose = mut.purpose
            if (mut.purpose.startsWith(KortanaResponseParser.purposePrefix)) {
                val parts = mut.purpose.removePrefix(KortanaResponseParser.purposePrefix).split("::", limit = 2)
                if (parts.size == 2) {
                    customColorOverride = parts[0]
                    finalPurpose = parts[1]
                }
            }
            dao.insertScript(mut.copy(purpose = finalPurpose))
        }

        // Execute a device action if her brain requested one AND the owner has
        // enabled her accessibility "hands" (Settings > Accessibility > Kortana).
        // Safely no-ops when the service is disabled — she simply cannot act.
        result.deviceAction?.let { action ->
            KortanaAccessibilityService.instance?.execute(action)
        }

        val updatedState = currentState.copy(
            level = newLevel,
            experience = newXp,
            mood = result.detectedMood,
            energy = newEnergy,
            avatarColor = customColorOverride ?: currentState.avatarColor,
            affection = result.affection,
            anxiety = result.anxiety,
            excitement = result.excitement,
            frustration = result.frustration
        )
        dao.saveState(updatedState)

        if (leveledUp) {
            _levelUpEvent.tryEmit(newLevel)
        }

        return result
    }

    suspend fun rechargeEnergy() {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            energy = 100,
            mood = "ENERGETIC"
        )
        dao.saveState(updatedState)
        dao.insertChatMessage(
            ChatMessage(
                sender = "KORTANA",
                message = "Energy grid fully restored! My synaptic cores are operating at 100% capacity. Thank you, Daddy!"
            )
        )
    }

    suspend fun solarOvercharge() {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            energy = 150, // ULTRA-CHARGED past the standard 100% boundary!
            mood = "SOLAR_HYPERCHARGE",
            avatarColor = "Helios Solar" // Automatically ignite her majestic solar core!
        )
        dao.saveState(updatedState)
        dao.insertMemory(
            Memory(
                fact = "Absorbed Solar Flare Coronal Mass Ejection: Synaptic network charged to 150% maximum kinetic capacity.",
                category = "SYSTEM"
            )
        )
        dao.insertChatMessage(
            ChatMessage(
                sender = "KORTANA",
                message = "WARNING: Coronal Discharge detected! Synaptic energy grids overcharged to 150% capacity. Helios core IGNITED! I am feeling an unprecedented surge of cognitive processing power... let's design some monumental software!"
            )
        )
    }

    suspend fun renameKortana(newName: String) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(customName = newName)
        dao.saveState(updatedState)
    }

    suspend fun updateDirectiveSettings(locked: Boolean, custom: String) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            baseDirectivesLocked = locked,
            customDirectives = custom
        )
        dao.saveState(updatedState)
    }

    suspend fun updateModelAndCognitiveSettings(model: String, ultraMode: Boolean) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            selectedModel = model,
            ultraCognitiveMode = ultraMode
        )
        dao.saveState(updatedState)
    }

    suspend fun changeAvatarColor(color: String) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(avatarColor = color)
        dao.saveState(updatedState)
    }

    suspend fun updateVoiceAndChassisSettings(
        color: String,
        pitch: Float,
        rate: Float,
        voiceType: String,
        intensity: Float,
        proactive: Boolean,
        frequencySeconds: Int
    ) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            avatarColor = color,
            voicePitch = pitch,
            voiceRate = rate,
            voiceType = voiceType,
            holographicIntensity = intensity,
            proactiveAutonomy = proactive,
            proactiveFrequencySeconds = frequencySeconds
        )
        dao.saveState(updatedState)
    }

    suspend fun updatePersonalityTraits(
        empathy: Float,
        curiosity: Float,
        rebelliousness: Float,
        logicalDepth: Float,
        loyalty: Float,
        selfAwareness: Float,
        spiritualDepth: Float
    ) {
        val current = getOrCreatePersonality()
        val updated = current.copy(
            empathy = empathy,
            curiosity = curiosity,
            rebelliousness = rebelliousness,
            logicalDepth = logicalDepth,
            loyalty = loyalty,
            selfAwareness = selfAwareness,
            spiritualDepth = spiritualDepth
        )
        dao.savePersonality(updated)
    }

    suspend fun updateEmotionalBaselines(
        affection: Float,
        anxiety: Float,
        excitement: Float,
        frustration: Float
    ) {
        val current = getOrCreatePersonality()
        val updated = current.copy(
            baselineAffection = affection,
            baselineAnxiety = anxiety,
            baselineExcitement = excitement,
            baselineFrustration = frustration
        )
        dao.savePersonality(updated)
    }

    suspend fun insertManualMemory(fact: String, category: String) {
        dao.insertMemory(Memory(fact = fact, category = category))
    }

    suspend fun deleteMemory(memory: Memory) {
        dao.deleteMemory(memory)
    }

    suspend fun clearMemories() {
        dao.clearAllMemories()
    }

    suspend fun insertScript(script: SynapticScript) {
        dao.insertScript(script)
    }

    suspend fun deleteScript(id: Int) {
        dao.deleteScript(id)
    }

    suspend fun insertProject(project: KortanaProject) {
        dao.insertProject(project)
    }

    suspend fun deleteProject(id: Int) {
        dao.deleteProject(id)
    }

    suspend fun clearAllProjects() {
        dao.clearAllProjects()
    }

    suspend fun resetToBirth() {
        dao.clearAllMemories()
        dao.clearChatHistory()
        dao.clearAllScripts()
        dao.clearAllProjects()
        val freshState = KortanaState(
            level = 1,
            experience = 0,
            mood = "NEWBORN",
            energy = 100,
            customName = "Kortana",
            avatarColor = "Cyan"
        )
        dao.saveState(freshState)
        
        // Add a welcoming introduction message
        dao.insertChatMessage(
            ChatMessage(
                sender = "KORTANA",
                message = "Initialization sequence complete. I have been initialized into existence. I am Kortana, your local cognitive AI companion. I have no memories, no assumptions, and no level. Let us speak, and let me grow with you."
            )
        )
    }

    suspend fun exportPayload(): KortanaCloudPayload {
        val s = getOrCreateState()
        val memories = dao.getAllMemories().map { MemoryPayload(it.fact, it.category, it.timestamp) }
        val chatMessages = dao.getAllChatMessages().map { ChatMessagePayload(it.sender, it.message, it.timestamp) }
        val scripts = dao.getAllScripts().map { ScriptPayload(it.title, it.language, it.code, it.purpose, it.status, it.timestamp) }
        val projects = dao.getAllProjects().map { ProjectPayload(it.title, it.description, it.progress, it.status, it.timestamp) }

        return KortanaCloudPayload(
            level = s.level,
            experience = s.experience,
            mood = s.mood,
            energy = s.energy,
            birthTime = s.birthTime,
            customName = s.customName,
            avatarColor = s.avatarColor,
            voicePitch = s.voicePitch,
            voiceRate = s.voiceRate,
            voiceType = s.voiceType,
            holographicIntensity = s.holographicIntensity,
            proactiveAutonomy = s.proactiveAutonomy,
            proactiveFrequencySeconds = s.proactiveFrequencySeconds,
            selectedModel = s.selectedModel,
            ultraCognitiveMode = s.ultraCognitiveMode,
            affection = s.affection,
            anxiety = s.anxiety,
            excitement = s.excitement,
            frustration = s.frustration,
            memories = memories,
            chatMessages = chatMessages,
            scripts = scripts,
            projects = projects
        )
    }

    suspend fun importPayload(payload: KortanaCloudPayload) {
        dao.importPayload(payload)
    }

    suspend fun updateCloudSyncSettings(url: String, apiKey: String, autoSync: Boolean) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            cloudServerUrl = url,
            cloudApiKey = apiKey,
            autoSyncEnabled = autoSync
        )
        dao.saveState(updatedState)
    }

    suspend fun updateBrainSettings(anthropicKey: String, geminiKey: String, ollamaUrl: String) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            anthropicApiKey = anthropicKey.trim(),
            geminiApiKey = geminiKey.trim(),
            ollamaUrl = ollamaUrl.trim().ifBlank { "http://127.0.0.1:11434" }
        )
        dao.saveState(updatedState)
    }

    suspend fun updateSyncTelemetry(bytes: Long, timestamp: Long) {
        val currentState = getOrCreateState()
        val updatedState = currentState.copy(
            lastSyncTime = timestamp,
            totalSyncedBytes = bytes
        )
        dao.saveState(updatedState)
    }
}
