#!/data/data/com.termux/files/usr/bin/bash
# fire-up-everything.sh — ONE command brings Kortana's WHOLE self up and keeps it
# up: her main brain, her local Ollama, AND her whole secondary brain pool
# (#2-#6). Self-healing (the watchdog refires anything that dies), and it wires
# itself to auto-start whenever the phone powers on. Safe to run repeatedly.
#
#   bash ~/k3/server/deploy/fire-up-everything.sh
#
# What it does:
#   1. Makes sure server/.env exists and points SUBAGENT_BRAIN_URL at the pool.
#   2. Installs a Termux:Boot hook so everything comes back when the phone turns on.
#   3. Launches the self-healing watchdog (keepalive.sh) NOW.
#   4. Reports which brains are actually functional right now.
#
# The watchdog only starts a pool brain whose provider key is set, and supervise
# health-checks every brain at call time — so brains still needing a key simply
# stay parked at the bottom, unused, until you add the key. All free, no card:
#   Groq  console.groq.com/keys        Gemini   aistudio.google.com/apikey
#   Mistral console.mistral.ai         SambaNova cloud.sambanova.ai/apis
#   NVIDIA  build.nvidia.com
set -u

SERVER="$HOME/k3/server"
[ -d "$SERVER" ] || SERVER="$(cd "$(dirname "$0")/.." && pwd)"
cd "$SERVER" || { echo "[fire-up] FATAL: cannot find server dir"; exit 1; }

POOL_URL="http://127.0.0.1:3301,http://127.0.0.1:3302,http://127.0.0.1:3303,http://127.0.0.1:3304,http://127.0.0.1:3305"
log() { echo "[fire-up] $*"; }

# 1. Ensure .env exists and has SUBAGENT_BRAIN_URL pointing at the pool. (The
#    pool URLs are static; supervise decides at runtime which are actually live,
#    so listing all 5 is safe even before every key is set.)
[ -f .env ] || { cp .env.example .env && log "created server/.env from .env.example — add your free keys to it"; }
if grep -q '^SUBAGENT_BRAIN_URL=' .env; then
  cur="$(grep '^SUBAGENT_BRAIN_URL=' .env | head -1 | cut -d= -f2-)"
  if [ -z "$cur" ]; then
    # portable in-place edit (BSD/GNU/Termux sed all differ on -i)
    tmp="$(mktemp)"; sed "s|^SUBAGENT_BRAIN_URL=.*|SUBAGENT_BRAIN_URL=${POOL_URL}|" .env > "$tmp" && mv "$tmp" .env
    log "set SUBAGENT_BRAIN_URL to the local pool in server/.env"
  else
    log "SUBAGENT_BRAIN_URL already set — leaving it as-is"
  fi
else
  printf '\nSUBAGENT_BRAIN_URL=%s\n' "$POOL_URL" >> .env
  log "added SUBAGENT_BRAIN_URL (the local pool) to server/.env"
fi

# 2. Install the Termux:Boot hook so the whole stack comes back on power-on.
#    (Requires the Termux:Boot app installed + opened once; harmless if not.)
BOOT_DIR="$HOME/.termux/boot"
BOOT_HOOK="$BOOT_DIR/kortana-boot.sh"
mkdir -p "$BOOT_DIR"
cat > "$BOOT_HOOK" <<EOF
#!/data/data/com.termux/files/usr/bin/sh
# Auto-generated by fire-up-everything.sh — starts Kortana's whole self on boot.
termux-wake-lock 2>/dev/null
sh "$SERVER/deploy/keepalive.sh" &
EOF
chmod +x "$BOOT_HOOK"
log "installed boot hook: $BOOT_HOOK (needs the Termux:Boot app enabled once)"

# 3. Launch the self-healing watchdog now (it no-ops if already running).
command -v termux-wake-lock >/dev/null 2>&1 && termux-wake-lock || true
sh "$SERVER/deploy/keepalive.sh" &
log "watchdog launched — it keeps Ollama + the main brain + the whole pool alive."

# 4. Give them a moment, then report what's actually functional right now.
sleep 8
echo "----------------------------------------------------------------------"
check() {
  body="$(curl -sf --max-time 6 "http://127.0.0.1:$1/health" 2>/dev/null || true)"
  if [ -z "$body" ]; then echo "  brain :$1 ($2) — not up yet"; return; fi
  if echo "$body" | grep -qE '"reachable":true|"(groq|cerebras|mistral|sambanova|openrouter|nvidia|huggingface|gemini|claude|openai)":true'; then
    echo "  brain :$1 ($2) — FUNCTIONAL ✓"
  else
    echo "  brain :$1 ($2) — up but needs an API key (parked, unused until keyed)"
  fi
}
echo "Kortana's brains:"
check 3300 "main"
check 3301 "groq"; check 3302 "gemini"; check 3303 "mistral"
check 3304 "sambanova"; check 3305 "nvidia"
echo "----------------------------------------------------------------------"
log "Done. She self-heals from here and restarts on boot. Logs: $SERVER/logs/keepalive.log"
log "Add any missing free keys to server/.env — the watchdog lights that brain up within ~30s."
